apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.namespace.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type}}