apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: sandbox
spec:
  selector:
    app: sandbox
  ports:
    - port: 3111
      targetPort: 4111
#      protocol: TCP
      nodePort: 32111
  type: NodePort