# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace:
  name: prod

replicaCount: 5

image:
  repository: dangrom/techtrends
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 7111
  targetPort: 7111
  protocal: TCP

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  name: techtrends
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 350m
    memory: 128Mi

containerPort: 3111

livenessProbe: /healthz
livenessProbePort: 3111
readinessProbe: /metrics
readinessProbePort: 3111

